# Generated by Django 3.2.5 on 2021-07-19 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tobacco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование товара')),
                ('slug', models.SlugField(unique=True)),
                ('product_image', models.ImageField(upload_to='', verbose_name='Изображение товара')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('taste', models.CharField(max_length=255, verbose_name='Вкус табака')),
                ('strength', models.CharField(max_length=255, verbose_name='Крепость табака')),
                ('structure', models.CharField(max_length=255, verbose_name='Нарезка табака')),
                ('size', models.CharField(max_length=255, verbose_name='Возможные граммовки')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hookah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование товара')),
                ('slug', models.SlugField(unique=True)),
                ('product_image', models.ImageField(upload_to='', verbose_name='Изображение товара')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('high', models.CharField(max_length=255, verbose_name='Длина шахты')),
                ('in_material', models.CharField(max_length=255, verbose_name='Материал шахты')),
                ('out_material', models.CharField(max_length=255, verbose_name='Материал накладки')),
                ('pull', models.CharField(max_length=255, verbose_name='Тяга')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
