# Generated by Django 3.2.5 on 2021-07-20 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_somemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SomeModel',
        ),
    ]
